name: Latest Medium posts workflow
on:
  # schedule:
    # Runs at 6am EST every day
    # - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update the README with latest Medium posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM"
          commit_message: "Updated README with the latest Medium posts"
          feed_list: "https://david-m-precopia.medium.com/"
