name: Latest Medium posts workflow
on:
  schedule:
    # Runs at 6am every Monday
    - cron: '0 6 * * 1'

jobs:
  update-readme-with-blog:
    name: Update the README with latest Medium posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM-POSTS-LISTS"
          commit_message: "Updated README with the latest Medium posts"
          feed_list: "https://medium.com/feed/@david.m.precopia"
